export default {
  USERS: {
    CREATE_USER: 'ACTIONS_CREATE_USER'
  },
  TRIPS: {
    INIT: 'ACTIONS_INITIALIZE_TRIPS_DATA',
    NEW_TRIP: 'ACTION_NEW_TRIP',
    UPDATE_TRIP: 'ACTION_UPDATE_TRIP'
  }
}